version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd src
      - npm install
  build:
    commands:
      - npm run build
      - cd ..
      - cp appspec.yml src/build/
      - mkdir -p src/build/scripts
      - cp scripts/install.sh src/build/scripts/

artifacts:
  files:
    - '**/*'
  base-directory: src/build
